#! /bin/sh

# config options
bspc config border_width            4
bspc config window_gap              9
bspc config split_ratio             0.5
bspc config history_aware_focus     true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# colors
bspc config normal_border_color     "#2b303b"
bspc config focused_border_color    "#a7adba"
bspc config presel_feedback_color   "#a7adba"

# add desktops
bspc monitor -d                     I II III IV V VI VII VIII IX X

# rules

# autostart
mpd &
compton &
feh --no-fehbg --randomize --bg-scale "$HOME/Imágenes/Backgrounds"
